document.writeln("    <div id=\'footer\'>");
document.writeln("");
document.writeln("");
document.writeln("");
document.writeln("    <div class=\'one-fourth\'>");
document.writeln("        <h3>常用品牌官网</h3>");
document.writeln("            <ul class=\'footer_links\'>");
document.writeln("                <li><a href=\'http://www.cn.onkyo.com/2018newsite/\'>ONKYO/安桥</a></li>");
document.writeln("                <li><a href=\'http://www.denon.com.cn/cn\'>DENON/天龙</a></li>");
document.writeln("                <li><a href=\'https://www.bose.cn/zh_cn/index.html\'>BOSE/博士</a></li>");
document.writeln("                <li><a href=\'https://cn.jbl.com/\'>JBL/杰宝</a></li>");
document.writeln("            </ul>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    <!-- Second Column -->");
document.writeln("    ");
document.writeln("    <div class=\'one-fourth\'>");
document.writeln("        <h3>&nbsp;</h3>");
document.writeln("            <ul class=\'footer_links\'>");
document.writeln("                <li><a href=\'http://www.pioneer-twn.com.tw/p1-product_type.asp\'>PIONEER/先锋</a></li>");
document.writeln("                <li><a href=\'http://www.integra.com.cn/\'>INTEGRA/英桥</a></li>");
document.writeln("                <li><a href=\'https://mksound.com/\'>M&KSOUND/MK</a></li>");
document.writeln("                <li><a href=\'http://velodyneacoustics.com/\'>VELODYNE/威力登</a></li>");
document.writeln("            </ul>");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    <!-- Third Column -->");
document.writeln("    ");
document.writeln("    <div class=\'one-fourth\'>");
document.writeln("        <h3>网页版权声明</h3>");
document.writeln("        本网站(网站地址)刊载的所有内容,包括文字、图片、音频、视频、软件、程序、以及网页版式设计等均在网上搜集。<br>");
document.writeln("		本网站内容原作者如不愿意在本网站刊登内容,请及时通知本站,予以删除。        ");
document.writeln("    </div>");
document.writeln("    ");
document.writeln("    <!-- Fourth Column -->");
document.writeln("    ");
document.writeln("    <div class=\'one-fourth last\'>");
document.writeln("        <h3>快捷联系</h3>");
document.writeln("            <a href=\'tencent://AddContact/?fromId=50&fromSubId=1&subcmd=all&uin=1952097170\'><img src=\'https://dlav2014.github.io/img/qq.png\' ></a>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div style=\'clear:both\'></div>");
document.writeln("    ");
document.writeln("    </div> <!-- END footer -->");