document.writeln("<!DOCTYPE HTML>");
document.writeln("<head>");
document.writeln("    <title>合生创展数码科技有限公司</title>");
document.writeln("    <meta name=\'keywords\' content=\'create from keywords\'>");
document.writeln("    <meta http-equiv=\'Content-Type\' content=\'text/html; charset=utf-8\'>");
document.writeln("	<!-- CSS 代码 -->");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' media=\'screen\' href=\'style.css\'>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' media=\'screen\' href=\'menu/css/simple_menu.css\'>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' media=\'screen\' href=\'css/prettyPhoto.css\'/>");
document.writeln("		<link rel=\'stylesheet\' type=\'text/css\' href=\'css/gridNavigation.css\' />");
document.writeln("	<!-- CSS 代码 -->");
document.writeln("	<!-- 跳出代码 -->");
document.writeln("	        <script type=text/javascript src=\'http://libs.baidu.com/jquery/1.9.0/jquery.min.js\'></script>");
document.writeln("			<script type=\'text/javascript\'>");
document.writeln("        $(function () {");
document.writeln("            get_share();");
document.writeln("        });");
document.writeln("        ");
document.writeln("        function get_share(){");
document.writeln("            var user = getQueryString(\'user\');");
document.writeln("            var url = getQueryString(\'url\');");
document.writeln("            $.ajax({");
document.writeln("             type: \'get\',");
document.writeln("             async: false,");
document.writeln("             url: \'https://dlav2014.github.io\',");
document.writeln("             data:{user:user,url:url},");
document.writeln("             dataType: \'jsonp\',");
document.writeln("             jsonp: \'callback\',");
document.writeln("             jsonpCallback:\'checkHandler\',");
document.writeln("             success: function(data){");
document.writeln("                 window.location.href=data.url;");
document.writeln("             },");
document.writeln("         });");
document.writeln("        }");
document.writeln("        ");
document.writeln("        function getQueryString(name) {");
document.writeln("            var reg = new RegExp(\'(^|&)\' + name + \'=([^&]*)(&|$)\', \'i\');");
document.writeln("            var r = window.location.search.substr(1).match(reg);");
document.writeln("            if (r != null) return unescape(r[2]);");
document.writeln("            return null;");
document.writeln("        }");
document.writeln(" ");
document.writeln("        </script>");
document.writeln("");
document.writeln("	");
document.writeln("");
document.writeln("</head>");
document.writeln("");
document.writeln("<body>");
document.writeln("");
document.writeln("	<div class=\'header\'>");
document.writeln("   ");
document.writeln("	<!-- Logo商标 -->");
document.writeln("		");
document.writeln("		<div style=\'margin-left:-20px;margin-top:-50px;\'><a href=\'https://dlav2014.github.io\'>");
document.writeln("			<img src=\'https://dlav2014.github.io/img/logo.png\' alt=\'合生创展数码科技有限公司\' /></a>");
document.writeln("		</div>  ");
document.writeln("	<!-- Logo商标 -->");
document.writeln("");
document.writeln("");
document.writeln("	<!-- 导航条 -->");
document.writeln("	   <ol id=\'menu\'>");
document.writeln("				 <li class=\'active_menu_item\'><a href=\'https://dlav2014.github.io\' style=\'color:#FFF\'>首页</a>");
document.writeln("			");
document.writeln("				  <!-- sub menu -->");
document.writeln("			");
document.writeln("			<li><a href=\'#\'>产品类目</a>");
document.writeln("			");
document.writeln("				  <!-- sub menu -->");
document.writeln("				  <ol>     ");
document.writeln("					<li><a href=\'https://dlav2014.github.io/gongfang.html\'>影院功放</a></li>");
document.writeln("					<li><a href=\'https://dlav2014.github.io/yinxiang.html\'>音箱/低音炮</a></li>");
document.writeln("					<li><a href=\'https://dlav2014.github.io/touyingji.html\'>投影机/幕布</a></li>");
document.writeln("					<li><a href=\'#\'>专业设备</a></li>");
document.writeln("					<li><a href=\'#\'>配件</a></li>");
document.writeln("					<li><a href=\'#\'>智能控制</a></li>");
document.writeln("				  </ol>");
document.writeln("			</li><!-- end sub menu -->");
document.writeln("			<li><a href=\'https://dlav2014.github.io/elements.html\'>公司简介</a></li><strong></strong>");
document.writeln("			<li><a href=\'#\'>公司案例</a></li>");
document.writeln("");
document.writeln("			<li><a href=\'https://dlav2014.github.io/contact.html\'>联系我们</a></li>");
document.writeln("		</ol>");
document.writeln("		   </div> ");
document.writeln("	<!-- 导航条 -->");
document.writeln("");
document.writeln("");
document.writeln("   ");
document.writeln("    </div>");
document.writeln("");
document.writeln("  ");
document.writeln("");
document.writeln("</body>");
document.writeln("</html>");